version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: golf-ezz-postgres
    environment:
      POSTGRES_DB: golf_ezz
      POSTGRES_USER: golf_user
      POSTGRES_PASSWORD: golf_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - golf-ezz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U golf_user -d golf_ezz"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: golf-ezz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - golf-ezz-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: golf-ezz-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@golfezz.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - golf-ezz-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  golf-ezz-network:
    driver: bridge
